# Generated by Django 4.0.3 on 2022-03-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blogmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
