# Generated by Django 4.0.3 on 2022-03-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_blogmodel_view_count_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comment'),
        ),
    ]
