# Generated by Django 4.0.3 on 2022-03-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_blogmodel_comment_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='post_comment',
        ),
    ]
